---
rbenv:
  dest: "{{ ansible_env.HOME }}/.rbenv"
  repo: git://github.com/sstephenson/rbenv.git
ruby_build:
  dest: "{{ rbenv.dest }}/plugins/ruby-build"
  repo: git://github.com/sstephenson/ruby-build.git
executable:
  rbenv: "{{ rbenv.dest }}/bin/rbenv"
ruby:
  dependencies:
    -
      name: gdbm
    -
      name: libyaml
    -
      name: libffi
    -
      name: openssl
    -
      name: readline
