---
-
  name: Install rbenv
  git:
    depth=1
    dest="{{ rbenv.dest }}"
    recursive=no
    repo="{{ rbenv.repo }}"
-
  name: Install ruby-build
  git:
    depth=1
    dest="{{ ruby_build.dest }}"
    recursive=no
    repo="{{ ruby_build.repo }}"
-
  name: Install Rubies
  command: "{{ rbenv.dest }}/bin/rbenv install {{ item.version }}"
  args:
    creates: "{{ rbenv.dest }}/versions/{{ item.version }}"
  with_items: rubies
