---
-
  name: Install rbenv
  git:
    depth=1
    dest="{{ rbenv.dest }}"
    recursive=no
    repo="{{ rbenv.repo }}"
-
  name: Install ruby-build
  git:
    depth=1
    dest="{{ ruby_build.dest }}"
    recursive=no
    repo="{{ ruby_build.repo }}"
-
  name: Install Ruby's dependencies
  homebrew:
    name="{{ item.name }}"
    state="{{ item.state | default('present') }}"
    install_options="{{ item.install_options | default('') }}"
  with_items: ruby.dependencies
-
  name: Install Rubies
  command: "{{ rbenv.dest }}/bin/rbenv install --keep {{ item.version }}"
  args:
    creates: "{{ rbenv.dest }}/versions/{{ item.version }}"
  with_items: ruby_versions
  environment:
    CC: /usr/bin/clang
    CXX: /usr/bin/clang++
    MAKE_OPTS: "-j {{ ansible_processor_cores }}"
    RUBY_CONFIGURE_OPTS: "
      --with-arch={{ ansible_architecture }}
      --with-valgrind
      --with-out-ext=tk,tk/*
      --enable-shared
      --enable-pthread
      --disable-install-doc
      --disable-libedit
      --with-gdbm-dir={{ homebrew.dest }}/opt/gdbm
      --with-dbm-dir={{ homebrew.dest }}/opt/gdbm
      --with-dbm-type=gdbm_compat
      --with-libyaml-dir={{ homebrew.dest }}/opt/libyaml
      --with-libffi-dir={{ homebrew.dest }}/opt/libffi
      --with-openssl-dir={{ homebrew.dest }}/opt/openssl
      --with-readline-dir={{ homebrew.dest }}/opt/readline
      --with-opt-dir={{ homebrew.dest }}"
