---
-
  name: Tap Homebrew Cask
  homebrew_tap: name=caskroom/cask
-
  name: Install Homebrew Cask
  homebrew: name=brew-cask
-
  name: Install Casks
  homebrew_cask:
    name="{{ item.name }}"
  with_items: osx_apps.casks
