---
-
  name: Prepare config directory
  file: path="{{ karabiner.config_dir }}" state=directory
-
  name: Install private.xml
  file:
    path="{{ karabiner.config_dir }}/private.xml"
    src="{{ karabiner.source_private_xml }}"
    state=link
-
  name: Relaod private.xml
  command: "{{ karabiner.command }} reloadxml"
-
  name: Configure Karabiner
  command: "{{ karabiner.command }} set {{ item.name }} {{ item.value }}"
  with_items: karabiner.config
