---
-
  name: Install Homebrew
  git:
    depth=1
    dest="{{ homebrew.dest }}"
    recursive=no
    update=no
    repo="{{ homebrew.repo }}"
-
  name: Install essential packages from Homebrew
  homebrew:
    name="{{ item.name }}"
    state="{{ item.state | default('present') }}"
    install_options="{{ item.install_options | default('') }}"
  with_items: homebrew.packages
-
  name: Tap Homebrew Cask
  homebrew_tap: name=caskroom/cask
-
  name: Install Homebrew Cask
  homebrew: name=brew-cask
-
  name: Install Casks
  homebrew_cask:
    name="{{ item.name }}"
  with_items: homebrew.casks
-
  name: Fetch dotfiles
  git:
    dest="{{ dotfiles.dest }}"
    repo="{{ dotfiles.repo }}"
-
  name: Install private.xml
  command: mkdir -p "{{ karabiner.config_dir }}" && ln -sf "{{ dotfiles.dest }}/osx/keyremap4macbook/private.xml" "{{ karabiner.config_dir }}/private.xml"
    creates="{{ karabiner.config_dir }}/private.xml"
-
  name: Relaod private.xml
  command: "{{ karabiner.command }} reloadxml"
-
  name: Configure Karabiner
  command: "{{ karabiner.command }} set {{ item.name }} {{ item.value }}"
  with_items: karabiner.config
