---
-
  name: Check Homebrew installation
  stat:
    path="{{ homebrew.dest }}"
  register: homebrew_install
-
  name: Setup Homebrew directory
  file:
    path="{{ homebrew.dest }}"
    mode=0755
    owner=aereal
    group=staff
    state=directory
  sudo: yes
  when: homebrew_install.stat.isdir is not defined or not homebrew_install.stat.isdir
-
  name: Install Homebrew
  git:
    dest="{{ homebrew.dest }}"
    recursive=no
    repo="{{ homebrew.repo }}"
    accept_hostkey=yes
  when: homebrew_install.stat.isdir is not defined or not homebrew_install.stat.isdir
-
  name: Install essential packages from Homebrew
  homebrew:
    name="{{ item.name }}"
    state="{{ item.state | default('present') }}"
    install_options="{{ item.install_options | default('') }}"
  with_items: homebrew.packages
  environment:
    PATH: "{{ homebrew.dest }}/bin:{{ ansible_env.PATH }}"
-
  name: Link brewed applications
  command: "{{ homebrew.dest }}/bin/brew linkapps"
-
  name: Fetch dotfiles
  git:
    dest="{{ dotfiles.dest }}"
    repo="{{ dotfiles.repo }}"
    update=no
-
  name: Configure ComputerName
  command: "scutil --set ComputerName {{ computer_name }}"
  sudo: yes
-
  name: Configure LocalHostName
  command: "scutil --set LocalHostName {{ local_host_name }}"
  sudo: yes
