---
-
  name: Install Homebrew
  git:
    depth=1
    dest="{{ homebrew.dest }}"
    recursive=no
    update=no
    repo="{{ homebrew.repo }}"
-
  name: Install essential packages from Homebrew
  homebrew:
    name="{{ item.name }}"
    state="{{ item.state | default('present') }}"
    install_options="{{ item.install_options | default('') }}"
  with_items: homebrew.packages
-
  name: Tap Homebrew Cask
  homebrew_tap: name=caskroom/cask
-
  name: Install Homebrew Cask
  homebrew: name=brew-cask
-
  name: Install Casks
  homebrew_cask:
    name="{{ item.name }}"
  with_items: homebrew.casks
-
  name: Fetch dotfiles
  git:
    dest="{{ dotfiles.dest }}"
    repo="{{ dotfiles.repo }}"
